name: test

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  # renovate: datasource=npm depName=pnpm
  PNPM_VERSION: 10.11.0

jobs:
  validate-preset:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 18.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm test
