name: test

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  # renovate: datasource=npm depName=pnpm
  PNPM_VERSION: 8.10.0

jobs:
  validate-preset:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3.6.0

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v3.8.2
        with:
          node-version: 18.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm test
