name: test

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  # renovate: datasource=npm depName=pnpm
  PNPM_VERSION: 7.18.1

jobs:
  validate-preset:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 14.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm test
